<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %} Anish Kumar {% endblock%}</title>
	<link rel="stylesheet" type="text/css" href="../resources/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="../resources/css/style.css">
	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<script src="../resources/js/jquery.min.js"></script>
	<script src="../resources/js/custom.js"></script>
</head>


<body>

	<div class="container" style="padding-top:40px;">

		{% block content %}
		{% endblock %}

	</div>


<script src="../resources/js/bootstrap.min.js"></script>
</body>
</html>